### ISSUE TITLE
Implement user public profile

### ISSUE THREAD

**Issue by mrkramar** [mrkramar/django-forum#1]
Users now only can see their own profile. Goal of this issue is to create public profiles.
This will later be used for sending personal messages, viewing user posts etc.

### DoD:
User can view other users profiles by clicking on their picture

**Comment by ivanch** [comment]
Working on it, though I won't be making the PM now.

**Comment by mrkramar** [comment]
Thank you for contributing :)
I will make another issue for personal messages.
