### ISSUE TITLE
Missing database tables

### ISSUE THREAD

**Issue by ivanch** [mrkramar/django-forum#3]
I tried to run the server, but I got some database errors, like "Table forum_topic does not exist" and "no such table: auth_user".
Am I missing something?

**Comment by mrkramar** [comment]
Hi :)

Try running this command:
`pyton3 manage.py migrate --run-syncdb`

and then create admin account by running:
`pyton3 manage.py createsuperuser`

Then you should be able to run the server and create some topics at `localhost:8000/admin`

Let me know if it works, I can also try to make sample database with some topics, if you are interested.

**Comment by ivanch** [comment]
Hey, thanks for the fast response!
It's working now.

Maybe you could create a Makefile to setup the environment, including things like installing requirements and database setup. An option to populate the database with some topics would be interesting as well.

**Comment by mrkramar** [comment]
Yeah, that is good idea, I will try to make something like that, or if you have some experience with that and you are willing to contribute, you can help me out :)

**Comment by ivanch** [comment]
I'd love to contribute ;)

Thanks for helping with this issue.

**Comment by mrkramar** [comment]
I have 2 open issues, but if you have any ideas, you can create new ones :)

Thank you
